"""initial migration

Revision ID: 859b1cb60cdc
Revises: 
Create Date: 2024-04-17 10:42:05.802597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '859b1cb60cdc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('composer',
                    sa.Column('composer_id', sa.Integer(), nullable=False),
                    sa.Column(
                        'name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('home_country', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.PrimaryKeyConstraint('composer_id')
                    )
    op.create_table('piece',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column(
                        'name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'alt_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('difficulty', sa.Integer(), nullable=False),
                    sa.Column('composer_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['composer_id'], ['composer.composer_id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('piece')
    op.drop_table('composer')
    # ### end Alembic commands ###
